name: "sort imports"

on:
  push:
    branches: [ master, main, testing-&-precommit ]
  pull_request:
    branches: [ master, main, testing-&-precommit ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run isort on the repository
      run: |
        pip install isort
        isort .
